/*
 * AGENTES BAFAR — Definiciones
 * Cada agente es una unidad de IA con misión específica, capacidades reales
 * (mapeables a un backend posterior) y métricas medibles.
 *
 * Cada tarea (taskPool[i]) tiene una secuencia de sub-pasos que el motor
 * va ejecutando uno por uno. Cada sub-paso emite un evento al feed y puede
 * tener un "payload" (el mensaje real, el lead, la decisión, etc.).
 */

export const AGENT_PALETTE = {
  centinela: { hue: '#e63946', soft: '#fef2f3', glow: 'rgba(230,57,70,0.18)' },
  atlas:     { hue: '#2563eb', soft: '#eff6ff', glow: 'rgba(37,99,235,0.18)' },
  mercurio:  { hue: '#d97706', soft: '#fffbeb', glow: 'rgba(217,119,6,0.18)' },
  vega:      { hue: '#9333ea', soft: '#faf5ff', glow: 'rgba(147,51,234,0.18)' },
  socrates:  { hue: '#16a34a', soft: '#f0fdf4', glow: 'rgba(22,163,74,0.18)' },
  coyote:    { hue: '#0891b2', soft: '#ecfeff', glow: 'rgba(8,145,178,0.18)' },
};

/*
 * Tipos de sub-paso (kind):
 *   - think   → modelo razonando · color gris
 *   - decide  → decisión tomada · color del agente
 *   - send    → mensaje/orden enviado al mundo · payload visible
 *   - wait    → esperando respuesta · animación
 *   - receive → respuesta recibida del mundo · payload visible
 *   - act     → acción consecuente (cupón emitido, ticket creado…)
 *   - outcome → resultado medible · genera valor o KPI
 */

export const AGENTS = [
  {
    id: 'centinela',
    name: 'Centinela',
    role: 'Retención Inteligente',
    codename: 'BAFAR-AI-01',
    mission: 'Detectar churn antes de que ocurra y reenganchar aliados de alto valor con la oferta correcta en el canal correcto.',
    description: 'Vigila 24/7 la actividad de los 3,247 aliados. Cuando detecta señales tempranas de abandono (baja en frecuencia, ticket o categorías), ejecuta una secuencia personalizada de reenganche.',
    capabilities: [
      'Modelo de propensión a churn (XGBoost · 89% AUC)',
      'Mensajería WhatsApp Business API',
      'Cupones dinámicos vía BAFAR Puntos',
      'Escalamiento a llamada del SAT humano',
    ],
    dataSources: ['Pedidos · 12M ventana', 'CRM aliados', 'Historial Puntos', 'Logs Academy'],
    cycleSec: 24,
    autonomy: 0.75,
    today: { actions: 47, success: 38, recovered: 12, valueMXN: 142000 },
    week: { actions: 312, recovered: 89, valueMXN: 982000 },
    accuracy: 89,
    valueSparkline: [42, 58, 71, 64, 89, 112, 142],
    taskPool: [
      {
        aliado: 'El Tacazo MTY',
        ciudad: 'Monterrey',
        diasInactivo: 34,
        segmento: 'Hamburguesería',
        valor: 8400,
        actionLabel: 'WhatsApp + 2× Puntos por 7 días',
        subSteps: [
          { kind: 'think',   text: 'Evaluando aliado El Tacazo MTY · ventana 30d',                                     meta: 'modelo XGBoost' },
          { kind: 'decide',  text: 'Score churn: 0.84 (alta) · valor histórico $8,400/mes · decisión: reenganche',     meta: 'umbral 0.65' },
          { kind: 'send',    text: 'Enviando WhatsApp Business · plantilla "reactivacion_hb_v3"',
                             payload: {
                               type: 'whatsapp',
                               to: '+52 81 1234 5678',
                               channel: 'WhatsApp Business · plantilla aprobada',
                               body: 'Hola Diego, soy Lucia del equipo BAFAR. Notamos que no nos has pedido en 34 días — todo bien? Te dejamos 2× Puntos en BAFAR Carnes por 7 días: cupón TACAZO2X. Vence sábado. ¿Te apoyamos con algo?',
                             } },
          { kind: 'wait',    text: 'Esperando ventana de respuesta · timeout 6h',                                       meta: 'auto-escala a SAT humano si timeout' },
          { kind: 'receive', text: 'Aliado respondió en 17 min · sentimiento positivo (0.82)',
                             payload: { type: 'reply', from: 'El Tacazo MTY · Diego', body: '¡Hola! Sí, ando con poca caja. Va el cupón, gracias!' } },
          { kind: 'act',     text: 'Cupón TACAZO2X activado · 2× Puntos en BAFAR Carnes · 7 días',                      meta: 'ledger Puntos · ID TXN-9842' },
          { kind: 'outcome', text: 'Pedido confirmado +$2,400 MXN · churn evitado · KPI recuperación +1',               meta: '+$2,400 MXN al ledger del día' },
        ],
      },
      {
        aliado: 'Pizzería Don Memo',
        ciudad: 'Chihuahua',
        diasInactivo: 22,
        segmento: 'Pizzería',
        valor: 12200,
        actionLabel: 'Llamada SAT prioritaria + bundle SABORI',
        subSteps: [
          { kind: 'think',   text: 'Detectado: drop 60% en pedidos SABORI vs cohort histórica',                         meta: 'top 3% en valor · $12.2K/mes' },
          { kind: 'decide',  text: 'Riesgo alto · escalando a SAT humano (no WhatsApp masivo)',                         meta: 'autonomía agente limitada en top-100' },
          { kind: 'send',    text: 'Creando ticket prioritario en CRM · asignando a Karla L. (SAT Chihuahua)',
                             payload: {
                               type: 'crm',
                               channel: 'CRM · ticket #CTNL-1842 · prioridad ALTA',
                               body: 'Llamar HOY antes de 18:00. Ofrecer: bundle SABORI 12% off + 90 días extensión a Puntos por vencer. Contexto: 22 días sin pedido, antes pedía $12K/mes regular.',
                             } },
          { kind: 'wait',    text: 'SAT confirma llamada agendada para 15:30',                                          meta: 'compromiso humano' },
          { kind: 'receive', text: 'Karla L. reporta: aliado cambió de proveedor por 1 mes · negociado regreso',
                             payload: { type: 'reply', from: 'Karla L. · SAT Chihuahua', body: 'Hablé con Memo. Acepta volver si le mantenemos los precios de Marzo en SABORI. Le mandé el bundle.' } },
          { kind: 'act',     text: 'Aplicando precio acordado · bloqueando 90 días · notificando a Pricing',            meta: 'precio congelado · auditado' },
          { kind: 'outcome', text: 'Aliado recuperado · LTV protegido ~$146K anual',                                    meta: 'evita pérdida $146K LTV' },
        ],
      },
      {
        aliado: 'Burger Boss CDMX',
        ciudad: 'CDMX',
        diasInactivo: 41,
        segmento: 'Hamburguesería',
        valor: 6800,
        actionLabel: 'Cupón BAFAR Carnes 15% + recordatorio',
        subSteps: [
          { kind: 'think',   text: 'Cohort similar (n=82): 31% reactivó con cupón 15% en BAFAR Carnes',                 meta: 'inferencia causal' },
          { kind: 'decide',  text: 'Aprobado cupón 15% · costo esperado $340 · uplift esperado $2,100',                 meta: 'ROI 6.1×' },
          { kind: 'send',    text: 'WhatsApp + push a app · canal redundante',
                             payload: {
                               type: 'whatsapp',
                               to: '+52 55 5544 1122',
                               channel: 'WhatsApp + Push app BAFAR Aliados',
                               body: 'Hola Burger Boss! Te extrañamos. 15% off en BAFAR Carnes esta semana con cupón BBOSS15. ¿Quieres que te lo pasemos para tu próximo pedido?',
                             } },
          { kind: 'wait',    text: 'Mensaje entregado · leído a los 4 min · sin respuesta aún',                         meta: 'esperando 6h' },
          { kind: 'receive', text: 'Sin respuesta en 6h · escalando con llamada SAT',                                   meta: 'reintento canal voz' },
          { kind: 'act',     text: 'Asignado a SAT Centro · llamada en cola',                                           meta: 'ticket #CTNL-1843' },
          { kind: 'outcome', text: 'Pendiente · ETA recuperación 48h',                                                  meta: 'medirá en 48h' },
        ],
      },
      {
        aliado: 'El Truck Loco',
        ciudad: 'Monterrey',
        diasInactivo: 18,
        segmento: 'Food Truck',
        valor: 9600,
        actionLabel: 'WhatsApp + reactivar SABORI',
        subSteps: [
          { kind: 'think',   text: 'Patrón: dejó de pedir SABORI tras 6 meses constantes',                              meta: 'feature drop' },
          { kind: 'decide',  text: 'Hipótesis: cambio de menú · ofrecer combo SABORI + LA CHONA',                       meta: 'cross-sell adyacente' },
          { kind: 'send',    text: 'WhatsApp con combo personalizado',
                             payload: {
                               type: 'whatsapp',
                               to: '+52 81 2233 4455',
                               channel: 'WhatsApp Business',
                               body: 'Hey Truck Loco, ¿probaste el nuevo combo SABORI + LA CHONA? Sale 10% más barato que pedirlos por separado. Te dejo el link: bafar.al/combo-tl',
                             } },
          { kind: 'receive', text: 'Aliado abrió el link · agregó al carrito · no terminó',                             meta: 'señal de interés' },
          { kind: 'act',     text: 'Reminder automático en 24h · cupón extra 5% si convierte',                          meta: 'cart recovery flow' },
          { kind: 'outcome', text: 'En seguimiento · prob. conversión 64%',                                             meta: 'observando' },
        ],
      },
      {
        aliado: 'Wings Factory GDL',
        ciudad: 'Guadalajara',
        diasInactivo: 28,
        segmento: 'Hamburguesería',
        valor: 7200,
        actionLabel: 'Promo 3×2 en alitas',
        subSteps: [
          { kind: 'think',   text: 'Categoría dominante: alitas (54% del histórico)',                                   meta: 'mix analysis' },
          { kind: 'decide',  text: 'Promo 3×2 · vigencia 5 días · sin canibalizar margen',                              meta: 'margen objetivo ≥18%' },
          { kind: 'send',    text: 'WhatsApp con promo y deadline',
                             payload: {
                               type: 'whatsapp',
                               to: '+52 33 8877 5544',
                               channel: 'WhatsApp Business',
                               body: 'Wings Factory, esta semana 3×2 en alitas BAFAR. Solo hasta el domingo. Cupón WINGS3X2. ¿Quieres que te bloqueemos inventario?',
                             } },
          { kind: 'receive', text: 'Respondió: pidió bloquear 80kg para el viernes',                                    meta: 'demanda confirmada' },
          { kind: 'act',     text: 'Inventario reservado · alerta a logística CEDIS Guadalajara',                       meta: 'pre-orden' },
          { kind: 'outcome', text: 'Recuperado · pedido $1,840 confirmado · seguimiento 30d',                           meta: '+$1,840 MXN inmediato' },
        ],
      },
      {
        aliado: 'La Parrillada Tijuana',
        ciudad: 'Tijuana',
        diasInactivo: 52,
        segmento: 'Cocina',
        valor: 5400,
        actionLabel: 'Encuesta + cupón recovery',
        subSteps: [
          { kind: 'think',   text: 'Más de 50d sin pedido · churn casi seguro (prob 91%)',                              meta: 'caso difícil' },
          { kind: 'decide',  text: 'Primero entender por qué se fue · luego ofrecer · no spammear',                     meta: 'jugada de fidelidad' },
          { kind: 'send',    text: 'Encuesta de 1 pregunta vía WhatsApp',
                             payload: {
                               type: 'whatsapp',
                               to: '+52 664 999 2211',
                               channel: 'WhatsApp Business',
                               body: 'Hola La Parrillada, soy Lucia de BAFAR. Solo una pregunta: ¿qué hicimos mal? (precio, calidad, servicio, otro). Sin pitch comercial. Solo queremos entender.',
                             } },
          { kind: 'receive', text: 'Respondió: "Precio de carne molida muy alto vs su competencia local"',              meta: 'señal valiosa · pasar a Mercurio' },
          { kind: 'act',     text: 'Reporte enviado a Mercurio (Pricing) · cupón compensatorio emitido',                meta: 'cross-agent handoff' },
          { kind: 'outcome', text: 'Insight valioso · cliente posiblemente perdido pero la red gana',                   meta: 'data valor estratégico' },
        ],
      },
    ],
    reasoning: [
      'Escaneando 3,247 aliados en busca de señales tempranas de churn…',
      'Detectados 47 aliados con drop >40% en frecuencia los últimos 14 días.',
      'Top 12 son de alto valor (ARR estimado >$8K/mes) — priorizando.',
      'Patrón: 8 de 12 son hamburgueserías → ofrecer pack BAFAR Carnes 15%.',
      'Generando mensajes personalizados con tono según historial conversacional.',
      'Disparando WhatsApp Business · ventana 09:00–18:00 hora local del aliado.',
      'Esperando window de respuesta 6h antes de escalar a SAT humano.',
    ],
  },

  /* ── ATLAS ─────────────────────────────────────────────────────── */
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'Expansión Geográfica',
    codename: 'BAFAR-AI-02',
    mission: 'Mapear clusters de demanda subatendidos y abrir mercados nuevos con leads pre-calificados.',
    description: 'Cruza datos de geolocalización, densidad de PyMEs, búsquedas locales y red propia para identificar dónde abrir el siguiente bafar-aliado antes que la competencia.',
    capabilities: [
      'Modelo de densidad geo (kernel density + Voronoi)',
      'Web scraping de directorios locales',
      'Scoring de leads (15 features)',
      'Asignación a fuerza de venta regional',
    ],
    dataSources: ['INEGI DENUE', 'Google Maps · Places', 'Red BAFAR', 'Datos de movilidad'],
    cycleSec: 30,
    autonomy: 0.6,
    today: { actions: 14, success: 14, recovered: 0, valueMXN: 380000 },
    week: { actions: 86, recovered: 0, valueMXN: 2140000 },
    accuracy: 82,
    valueSparkline: [180, 220, 260, 240, 310, 340, 380],
    taskPool: [
      {
        aliado: 'Cluster Pachuca-Tulancingo',
        ciudad: 'Hidalgo',
        segmento: 'Zona blanca',
        valor: 38,
        actionLabel: 'Asignar a SAT Centro · 38 leads',
        subSteps: [
          { kind: 'think',   text: 'Cargando matriz DENUE · 184K puntos PyMEs',                                         meta: 'INEGI · cierre 2025' },
          { kind: 'decide',  text: 'Densidad 47 PyMEs/km² · BAFAR penetración 4% · ¡cluster ganador!',                  meta: 'top 3% nacional' },
          { kind: 'send',    text: 'Generando lista de 38 leads scored',
                             payload: {
                               type: 'leads',
                               channel: 'CRM · folder Hidalgo-Centro',
                               leads: [
                                 { nombre: 'Hamburguesas La Plaza', score: 9.1, ciudad: 'Pachuca', tipo: 'Hamburguesería' },
                                 { nombre: 'Pizzas del Centro',     score: 8.8, ciudad: 'Pachuca', tipo: 'Pizzería' },
                                 { nombre: 'Tacos Don Pancho',      score: 8.6, ciudad: 'Tulancingo', tipo: 'Taquería' },
                                 { nombre: 'El Truck Hidalgo',      score: 8.4, ciudad: 'Tulancingo', tipo: 'Food Truck' },
                                 { nombre: 'Wings Plaza',           score: 8.2, ciudad: 'Pachuca', tipo: 'Hamburguesería' },
                                 { nombre: '+ 33 más con score >7', score: 0,   ciudad: '',          tipo: '' },
                               ],
                             } },
          { kind: 'wait',    text: 'Esperando aprobación de Dirección Comercial',                                       meta: 'humano in the loop' },
          { kind: 'receive', text: 'Aprobado · roadshow 2 semanas asignado',                                            meta: 'Director Comercial' },
          { kind: 'act',     text: 'Briefing automático a SAT Regional Centro · agenda generada',                       meta: 'calendario sincronizado' },
          { kind: 'outcome', text: 'Estimado: 12 aliados nuevos en 90 días · LTV $440K',                                meta: 'expansión $440K LTV' },
        ],
      },
      {
        aliado: 'Corredor Mexicali-San Luis',
        ciudad: 'BC',
        segmento: 'Frontera',
        valor: 22,
        actionLabel: 'Roadshow 2 semanas frontera',
        subSteps: [
          { kind: 'think',   text: 'Frontera norte · sin BAFAR en 80km · alta demanda B2B',                             meta: 'oportunidad blanca' },
          { kind: 'decide',  text: 'Aliados objetivo: cocinas industriales + food trucks',                              meta: '22 leads · score >7.5' },
          { kind: 'send',    text: 'Envío de plan de roadshow a SAT Noroeste',
                             payload: {
                               type: 'plan',
                               channel: 'Email + CRM',
                               body: 'Roadshow Mexicali-San Luis · 14 días · 22 visitas · KPI: 8 aliados firmados · presupuesto $84K',
                             } },
          { kind: 'wait',    text: 'SAT confirma equipo · 3 reps disponibles',                                          meta: 'capacidad ok' },
          { kind: 'act',     text: 'Roadshow inicia lunes · alertas configuradas',                                      meta: 'monitoreo diario' },
          { kind: 'outcome', text: 'En curso · 4 firmados en primera semana',                                           meta: '+4 aliados · ARR $51K' },
        ],
      },
      {
        aliado: 'Centro histórico Puebla',
        ciudad: 'Puebla',
        segmento: 'Centro urbano',
        valor: 31,
        actionLabel: 'Campaña piloto SABORI',
        subSteps: [
          { kind: 'think',   text: 'Búsquedas "queso pizza Puebla" subieron 38% mensual',                               meta: 'Google Trends + Places' },
          { kind: 'decide',  text: 'Lanzar campaña SABORI con 31 leads pizzerías centro',                               meta: 'foco SKU específico' },
          { kind: 'send',    text: 'Enviando paquete a SAT Puebla con muestras gratis',
                             payload: {
                               type: 'plan',
                               channel: 'CRM · campaña #ATLS-2031',
                               body: 'Visitas con muestras SABORI · 31 prospectos · cupón onboarding 20%',
                             } },
          { kind: 'receive', text: 'SAT reporta 18 muestras entregadas · alta receptividad',                            meta: 'señal positiva' },
          { kind: 'outcome', text: 'Pipeline $124K en 30 días · 7 cerrados',                                            meta: 'conversión 23%' },
        ],
      },
      {
        aliado: 'Tulum-Playa del Carmen',
        ciudad: 'Quintana Roo',
        segmento: 'Turismo',
        valor: 18,
        actionLabel: 'Sembrar antes de temporada alta',
        subSteps: [
          { kind: 'think',   text: 'Temporada alta empieza en 12 semanas · sembrar ahora',                              meta: 'estacionalidad QROO' },
          { kind: 'decide',  text: '18 leads turísticos · oferta de financiamiento de inventario',                      meta: 'value prop financiero' },
          { kind: 'send',    text: 'Envío de propuesta especial turística',
                             payload: { type: 'plan', channel: 'CRM', body: 'Propuesta: crédito de inventario · 60 días sin intereses · 18 prospectos' } },
          { kind: 'outcome', text: 'Pipeline $86K · cierre esperado en 6 semanas',                                      meta: 'pre-temporada' },
        ],
      },
    ],
    reasoning: [
      'Cargando matriz nacional de densidad PyMEs (DENUE + Places · 184K puntos).',
      'Identificando zonas con >40 PyMEs/km² y <2 aliados BAFAR.',
      'Cluster ganador: Pachuca-Tulancingo · 38 prospectos score >7/10.',
      'Cruzando con historial de aperturas exitosas (cohort similitud).',
      'Probabilidad de conversión estimada: 31% en primeros 90 días.',
      'Generando paquete de leads para SAT Regional Centro con scoring.',
      'Alerta enviada a Dirección Comercial · esperando aprobación.',
    ],
  },

  /* ── MERCURIO ──────────────────────────────────────────────────── */
  {
    id: 'mercurio',
    name: 'Mercurio',
    role: 'Pricing & Promo Optimizer',
    codename: 'BAFAR-AI-03',
    mission: 'Optimizar precios y multiplicadores de BAFAR Puntos con experimentación continua para maximizar margen sin sacrificar volumen.',
    description: 'Ejecuta cientos de A/B tests microsegmentados al mes. Ajusta dinámicamente multiplicadores de Puntos por marca, categoría y segmento de aliado para extraer el máximo valor.',
    capabilities: [
      'Multi-armed bandit (Thompson sampling)',
      'Causal inference (lift estimation)',
      'Elasticidad precio por SKU',
      'Auto-rollback si lift < umbral',
    ],
    dataSources: ['Catálogo SKUs', 'Transacciones', 'BAFAR Puntos ledger', 'Logs e-commerce'],
    cycleSec: 18,
    autonomy: 0.85,
    today: { actions: 23, success: 18, recovered: 0, valueMXN: 218000 },
    week: { actions: 162, recovered: 0, valueMXN: 1480000 },
    accuracy: 94,
    valueSparkline: [120, 145, 180, 162, 198, 210, 218],
    taskPool: [
      {
        aliado: 'Test #142 · Caperucita 2× Puntos',
        ciudad: 'Nacional',
        segmento: 'A/B vivo',
        valor: 240,
        actionLabel: 'Escalar a 100% de hamburgueserías',
        subSteps: [
          { kind: 'think',   text: 'Test #142 · 14 días corriendo · n=2,840 aliados',                                   meta: 'Thompson sampling' },
          { kind: 'decide',  text: 'Lift detectado: +14% · p-value 0.03 · significativo',                               meta: 'umbral p<0.05 ok' },
          { kind: 'send',    text: 'Aplicando variante B a 100% de hamburgueserías',
                             payload: {
                               type: 'experiment',
                               channel: 'Pricing engine · catálogo SKU',
                               variants: { A: '1× Puntos · base', B: '2× Puntos · ganadora' },
                               metrics: { uplift: '+14.2%', revenuePer1k: '$3,840', confidence: '97%' },
                             } },
          { kind: 'wait',    text: 'Pricing Manager (Sofía R.) en ventana de veto · 24h',                               meta: 'human override' },
          { kind: 'receive', text: 'Sin veto · auto-aplicado',                                                          meta: 'política agente 0.85' },
          { kind: 'act',     text: 'Catálogo actualizado · cohort 12,400 aliados',                                      meta: 'efectivo inmediato' },
          { kind: 'outcome', text: 'Margen incremental esperado +$320K MXN / 30 días',                                  meta: '+$320K mensuales' },
        ],
      },
      {
        aliado: 'Test #143 · SABORI Vol-discount',
        ciudad: 'Pizzerías',
        segmento: 'A/B vivo',
        valor: 180,
        actionLabel: 'Continuar acumulando · 4 días más',
        subSteps: [
          { kind: 'think',   text: 'Test #143 · 9 días · lift +6% pero p=0.18 (no significativo)',                       meta: 'aún ruidoso' },
          { kind: 'decide',  text: 'Esperar 4 días más antes de decidir · monitorear daily',                            meta: 'paciencia estadística' },
          { kind: 'send',    text: 'Reporte diario enviado a Pricing',
                             payload: { type: 'experiment', channel: 'Slack #pricing', body: '#143 día 9 · lift +6% p=0.18 · sigue corriendo' } },
          { kind: 'outcome', text: 'Test continúa · próxima evaluación en 96h',                                         meta: 'paciente' },
        ],
      },
      {
        aliado: 'Test #144 · BURR bundle',
        ciudad: 'CDMX',
        segmento: 'A/B vivo',
        valor: 96,
        actionLabel: 'Rollback automático',
        subSteps: [
          { kind: 'think',   text: 'Test #144 · 10 días · lift +2% · p=0.41',                                            meta: 'sin señal' },
          { kind: 'decide',  text: 'Por debajo del umbral mínimo · rollback automático',                                meta: 'política agente' },
          { kind: 'send',    text: 'Aplicando variante A en 100% (rollback)',
                             payload: { type: 'experiment', channel: 'Pricing engine', body: 'Variante B retirada · vuelve a precio base BURR' } },
          { kind: 'act',     text: 'Notificando a Pricing · lección aprendida registrada',                              meta: 'memoria del agente' },
          { kind: 'outcome', text: 'Sin pérdida · evitado escalar mal experimento',                                     meta: 'protección' },
        ],
      },
      {
        aliado: 'Pricing dinámico carne molida',
        ciudad: 'CHIH',
        segmento: 'Vivo',
        valor: 320,
        actionLabel: 'Tarifa horaria off-peak',
        subSteps: [
          { kind: 'think',   text: 'Análisis elasticidad: demanda off-peak -22% vs hora pico',                          meta: 'modelo elasticidad' },
          { kind: 'decide',  text: 'Aplicar tarifa -2% en horario 14:00-17:00 · piloto CHIH',                           meta: 'micro-segmento' },
          { kind: 'send',    text: 'Activando descuento dinámico en catálogo',
                             payload: { type: 'experiment', channel: 'Pricing engine · CHIH', body: 'Carne molida -2% 14:00-17:00 · piloto 14 días' } },
          { kind: 'receive', text: 'Pedidos en ventana +18% día 1 · margen mantenido',                                  meta: 'lectura inicial' },
          { kind: 'outcome', text: 'Esperado margen +$92K si se mantiene · escalable a NL/CDMX',                        meta: 'sembrado escalable' },
        ],
      },
    ],
    reasoning: [
      '162 experimentos activos · 18 en fase de escalado.',
      'Test #142 (Caperucita 2× Puntos) alcanzó significancia: +14% lift, p=0.03.',
      'Tamaño de muestra suficiente (n=2,840 aliados) — pasando a producción.',
      'Validando que no canibaliza con tests adyacentes (#138, #140).',
      'Estimación de impacto a 30 días: +$320K MXN en margen incremental.',
      'Notificando a Pricing Manager · auto-aplicar en 24h si no hay veto.',
      'Iniciando test #146 · BURR + ensalada · cohort 1,200 pizzerías.',
    ],
  },

  /* ── VEGA ──────────────────────────────────────────────────────── */
  {
    id: 'vega',
    name: 'Vega',
    role: 'Forecast de Demanda',
    codename: 'BAFAR-AI-04',
    mission: 'Pronosticar pedidos por marca, estado y semana para anclar supply chain y evitar quiebres o sobre-stock.',
    description: 'Modelo de series temporales (Prophet + LightGBM) que predice demanda con horizonte de 8 semanas. Alimenta planeación de producción y logística.',
    capabilities: [
      'Series temporales (Prophet + LGB)',
      'Detección de eventos (calendario MX)',
      'Confianza por intervalo (P10/P50/P90)',
      'Trigger automático a SAP supply',
    ],
    dataSources: ['Pedidos · 36M ventana', 'Calendario eventos', 'Precios competencia', 'Clima'],
    cycleSec: 28,
    autonomy: 0.7,
    today: { actions: 8, success: 7, recovered: 0, valueMXN: 0 },
    week: { actions: 42, recovered: 0, valueMXN: 0 },
    accuracy: 91,
    valueSparkline: [10.4, 10.6, 10.9, 11.0, 11.2, 11.4, 11.2],
    taskPool: [
      {
        aliado: 'Forecast Junio · BAFAR Carnes',
        ciudad: 'Nacional',
        segmento: 'Forecast',
        valor: 11.2,
        actionLabel: 'Confirmar orden producción',
        subSteps: [
          { kind: 'think',   text: 'Re-entrenando modelo con datos Mayo · 12,840 pedidos nuevos',                       meta: 'Prophet + LGB' },
          { kind: 'decide',  text: 'P50 nacional Junio: $11.2M · intervalo 87% confianza',                              meta: 'MAPE 3.4%' },
          { kind: 'send',    text: 'Generando orden de producción a SAP',
                             payload: {
                               type: 'forecast',
                               channel: 'SAP MRP · módulo demand-plan',
                               body: 'Junio: 1,840 toneladas BAFAR Carnes molida · +12% vs Mayo · Banda P10=1,720 P90=1,920',
                             } },
          { kind: 'wait',    text: 'Esperando confirmación de Planeación · 24h',                                        meta: 'control humano' },
          { kind: 'receive', text: 'Planeación confirmó ajuste · órdenes a planta Chihuahua',                           meta: 'aprobado' },
          { kind: 'outcome', text: 'Evita stockout estimado $2.4M · ROI agente alto',                                   meta: 'pérdida evitada $2.4M' },
        ],
      },
      {
        aliado: 'Forecast Junio · SABORI',
        ciudad: 'Nacional',
        segmento: 'Forecast',
        valor: 4.8,
        actionLabel: 'Subir producción +12% por Día Padre',
        subSteps: [
          { kind: 'think',   text: 'Detectado evento: Día del Padre (15 Jun)',                                          meta: 'calendario MX' },
          { kind: 'decide',  text: 'Spike esperado +18% en SABORI · cohort histórica 2023-2025',                        meta: 'evento confirmado' },
          { kind: 'send',    text: 'Enviando alerta a Planeación con ajuste',
                             payload: { type: 'forecast', channel: 'SAP MRP', body: 'SABORI Junio +12% prod · evento Día Padre · pedidos semana 24 +18%' } },
          { kind: 'act',     text: 'Producción ajustada · logística pre-posiciona inventario',                          meta: 'CEDIS preparados' },
          { kind: 'outcome', text: 'Captura del spike sin sobre-stock · ~$520K extra',                                  meta: 'oportunidad capturada' },
        ],
      },
      {
        aliado: 'Alerta · BURR escasez 8 sem',
        ciudad: 'NL',
        segmento: 'Riesgo',
        valor: 0.94,
        actionLabel: 'Acelerar producción Julio',
        subSteps: [
          { kind: 'think',   text: 'Inventario actual BURR < P90 forecast en 8 semanas',                                meta: 'señal temprana' },
          { kind: 'decide',  text: 'Riesgo de stockout 38% si no se acelera',                                           meta: 'umbral 25%' },
          { kind: 'send',    text: 'Alerta enviada a Operaciones · prioridad alta',
                             payload: { type: 'alert', channel: 'SAP MRP + Slack #ops', body: 'BURR riesgo stockout sem-8 · acelerar producción 14% en Julio' } },
          { kind: 'wait',    text: 'Esperando respuesta de Planta NL',                                                  meta: 'capacidad sujeta' },
          { kind: 'outcome', text: 'En revisión · ETA decisión 48h',                                                    meta: 'pendiente' },
        ],
      },
      {
        aliado: 'Forecast estacional LA CHONA',
        ciudad: 'Nacional',
        segmento: 'Forecast',
        valor: 1.6,
        actionLabel: 'Plan de drenaje de stock',
        subSteps: [
          { kind: 'think',   text: 'Caída esperada -22% en verano · estacionalidad fuerte',                             meta: 'patrón 5 años' },
          { kind: 'decide',  text: 'Recomendar drenaje suave · evitar sobre-stock JulAgo',                              meta: 'optimización inventario' },
          { kind: 'send',    text: 'Plan a Comercial: promo LA CHONA en hot-dogs verano',
                             payload: { type: 'forecast', channel: 'CRM Comercial', body: 'LA CHONA -22% esperado · activar promo "Verano Frío" · cupones 10%' } },
          { kind: 'outcome', text: 'Coordinación con Mercurio para experimento ad-hoc',                                 meta: 'cross-agent' },
        ],
      },
    ],
    reasoning: [
      'Re-entrenando modelo con datos cierre Mayo · 12,840 pedidos nuevos.',
      'Error de pronóstico Mayo: 3.4% (MAPE). Dentro de tolerancia (<5%).',
      'Pronóstico Junio nacional: $11.2M ±4% (intervalo 87% confianza).',
      'Detectado evento atípico: Día del Padre (15 Jun) — spike +18% SABORI.',
      'Alerta: BURR podría tener escasez semana 8 si no se acelera producción.',
      'Recomendación enviada a Planeación · ajustar orden 12% al alza.',
      'Próximo ciclo de re-entrenamiento: en 7 días.',
    ],
  },

  /* ── SÓCRATES ──────────────────────────────────────────────────── */
  {
    id: 'socrates',
    name: 'Sócrates',
    role: 'Curador Academy',
    codename: 'BAFAR-AI-05',
    mission: 'Cerrar brechas de conocimiento en cada aliado entregando el video correcto en el momento correcto.',
    description: 'Detecta señales de baja productividad (ticket bajo, márgenes pobres, alta merma) y recomienda contenido educativo personalizado del catálogo BAFAR Academy.',
    capabilities: [
      'Análisis de gap operativo por aliado',
      'Recomendación content-based + colaborativa',
      'Trigger educacional vía app/WhatsApp',
      'Medición de lift post-consumo',
    ],
    dataSources: ['Métricas operativas', 'Catálogo Academy', 'Watch-history', 'Encuestas NPS'],
    cycleSec: 22,
    autonomy: 0.8,
    today: { actions: 142, success: 118, recovered: 0, valueMXN: 84000 },
    week: { actions: 960, recovered: 0, valueMXN: 612000 },
    accuracy: 86,
    valueSparkline: [54, 62, 71, 68, 79, 82, 84],
    taskPool: [
      {
        aliado: '142 aliados · ticket <$1,500',
        ciudad: 'Nacional',
        segmento: 'Gap detectado',
        valor: 142,
        actionLabel: 'Push + WhatsApp con "Costeo de recetas"',
        subSteps: [
          { kind: 'think',   text: 'Detectados 142 aliados con ticket <$1,500 · gap rentabilidad',                       meta: 'cluster analysis' },
          { kind: 'decide',  text: 'Match: video "Costeo de recetas en 5 min" · cohort lift histórico +22%',            meta: 'recomendación content-based' },
          { kind: 'send',    text: 'Disparando push notif + WhatsApp recordatorio',
                             payload: {
                               type: 'whatsapp',
                               to: '142 aliados (batch)',
                               channel: 'Push BAFAR app + WhatsApp follow-up',
                               body: 'Tip BAFAR (5 min): "Costeo de recetas paso a paso". Aliados que lo vieron subieron su ticket +22%. Velo aquí 👉 bafar.al/c5',
                             } },
          { kind: 'wait',    text: 'Ventana de medición 30 días',                                                       meta: 'medición de lift' },
          { kind: 'receive', text: '89 aliados completaron el video (62% conversion)',                                  meta: '62% completion · arriba del promedio' },
          { kind: 'act',     text: 'Cohort etiquetado para seguimiento · medición ticket en 30d',                       meta: 'experimento corriendo' },
          { kind: 'outcome', text: 'Ticket promedio del cohort +18% en 30d · uplift $94/aliado',                        meta: '+$84K MXN ARR proyectado' },
        ],
      },
      {
        aliado: '38 hamburgueserías mid-tier',
        ciudad: 'CDMX',
        segmento: 'Mejora cocina',
        valor: 38,
        actionLabel: 'Insertar "Hamburguesa perfecta" en feed',
        subSteps: [
          { kind: 'think',   text: 'Hamburgueserías con NPS 6-7 (mid) · oportunidad de upskill',                         meta: 'segmento target' },
          { kind: 'decide',  text: 'Sugerir "La hamburguesa perfecta" (92% completion histórico)',                      meta: 'high signal' },
          { kind: 'send',    text: 'Inserción en feed semanal · 38 aliados',
                             payload: { type: 'feed', channel: 'BAFAR app · home feed', body: 'Video destacado al login · CTA "ver en 12 min"' } },
          { kind: 'outcome', text: 'Lift NPS +1.4 puntos en mes · más promotores',                                      meta: 'cualitativo +1.4pp' },
        ],
      },
      {
        aliado: '64 food trucks sin Academy',
        ciudad: 'Nacional',
        segmento: 'Onboarding',
        valor: 64,
        actionLabel: 'Email + gamificación',
        subSteps: [
          { kind: 'think',   text: '64 food trucks · sin login en Academy >30d',                                        meta: 'cold cohort' },
          { kind: 'decide',  text: 'Activar con gamificación: 500 puntos por primer video',                             meta: 'incentivo monetario' },
          { kind: 'send',    text: 'Email + WhatsApp con CTA puntos',
                             payload: {
                               type: 'whatsapp',
                               to: '64 aliados',
                               channel: 'WhatsApp + Email',
                               body: 'Reto BAFAR: mira tu primer video de Academy y ganas 500 Puntos automáticos. Solo esta semana. ¿Le entras?',
                             } },
          { kind: 'receive', text: '28 activaron (44%) · bueno para cold cohort',                                       meta: 'arriba del benchmark' },
          { kind: 'outcome', text: 'Onboarding desbloqueado · seguimiento 60d',                                         meta: 'fundación de hábito' },
        ],
      },
    ],
    reasoning: [
      'Analizando 838 aliados sin actividad reciente en Academy.',
      'Detectados 142 con ticket promedio <$1,500 — gap claro de rentabilidad.',
      'Match a video: "Costeo de recetas" (78% completion histórico).',
      'Aliados que vieron este video tuvieron +22% en ticket a 30 días.',
      'Personalizando timing: enviar martes 14:00 (hora de mayor apertura).',
      'Disparando notificación push + WhatsApp recordatorio en 24h.',
      'Midiendo lift en 60 días vs grupo control.',
    ],
  },

  /* ── COYOTE ────────────────────────────────────────────────────── */
  {
    id: 'coyote',
    name: 'Coyote',
    role: 'Anti-Fraude',
    codename: 'BAFAR-AI-06',
    mission: 'Proteger la red de patrones anómalos: redenciones falsas, pedidos sospechosos, abuso del programa Puntos.',
    description: 'Detección de anomalías en tiempo real sobre el ledger de Puntos y transacciones. Congela operaciones sospechosas y notifica al equipo de Riesgo.',
    capabilities: [
      'Isolation Forest (detección anomalías)',
      'Reglas IP/device/velocity',
      'Congelamiento de transacción',
      'Reportes a Compliance',
    ],
    dataSources: ['Ledger Puntos', 'Logs sesión', 'IP/device fingerprint', 'Histórico fraude'],
    cycleSec: 16,
    autonomy: 0.55,
    today: { actions: 12, success: 11, recovered: 0, valueMXN: 38000 },
    week: { actions: 78, recovered: 0, valueMXN: 184000 },
    accuracy: 96,
    valueSparkline: [18, 22, 28, 24, 32, 34, 38],
    taskPool: [
      {
        aliado: 'Anomalía · 7 redenciones mismo IP',
        ciudad: 'CDMX',
        segmento: 'Fraude alta',
        valor: 24000,
        actionLabel: 'Escalar a Compliance',
        subSteps: [
          { kind: 'think',   text: 'Detectadas 7 redenciones simultáneas desde IP 189.222.x.x · CDMX',                  meta: 'velocity check' },
          { kind: 'decide',  text: 'Isolation Forest score 0.94 · umbral crítico 0.85 · congelar',                      meta: 'auto-acción' },
          { kind: 'send',    text: 'Congelando 7 transacciones · auditoría iniciada',
                             payload: {
                               type: 'fraud',
                               channel: 'Ledger Puntos · módulo risk',
                               body: 'TXN #45782-45788 congeladas · monto total $24,000 · razón: velocity+IP',
                             } },
          { kind: 'wait',    text: 'Reporte enviado a Compliance · esperando dictamen 24h',                             meta: 'humano in the loop' },
          { kind: 'receive', text: 'Compliance: confirmado fraude · 5 de 7 cuentas falsas',                             meta: 'caso real' },
          { kind: 'act',     text: 'Bloqueo permanente · reporte a CONDUSEF · cuentas marcadas',                        meta: 'compliance flow' },
          { kind: 'outcome', text: 'Pérdida evitada $24K · IP en blacklist red BAFAR',                                  meta: '+$24K protegidos' },
        ],
      },
      {
        aliado: 'Aliado con pedidos duplicados',
        ciudad: 'GDL',
        segmento: 'Fraude media',
        valor: 4800,
        actionLabel: 'Verificación manual',
        subSteps: [
          { kind: 'think',   text: 'Pattern: 3 pedidos idénticos en <2 min · mismo aliado',                              meta: 'duplicate detection' },
          { kind: 'decide',  text: 'Probablemente error de UI · no congelar · enviar verificación',                     meta: 'sesgo benigno' },
          { kind: 'send',    text: 'Ticket SAT · llamar al aliado para confirmar',
                             payload: { type: 'crm', channel: 'CRM · ticket #COY-823', body: 'Verificar si quiso pedir 3 veces o fue error de doble clic' } },
          { kind: 'receive', text: 'Aliado confirma: error de doble clic · liberar 2 pedidos',                          meta: 'falso positivo' },
          { kind: 'outcome', text: 'Caso cerrado · ajustando regla para reducir falsos positivos',                      meta: 'aprendizaje agente' },
        ],
      },
      {
        aliado: 'Velocity check · cluster IPs',
        ciudad: 'CDMX',
        segmento: 'Fraude alta',
        valor: 18000,
        actionLabel: 'Bloqueo en cascada',
        subSteps: [
          { kind: 'think',   text: '12 cuentas mismo subnet · creadas en últimas 48h · patrones idénticos',             meta: 'fraud ring' },
          { kind: 'decide',  text: 'Banda organizada · bloqueo en cascada inmediato',                                    meta: 'política agresiva' },
          { kind: 'send',    text: 'Bloqueando 12 cuentas + alerta interna',
                             payload: { type: 'fraud', channel: 'Risk engine', body: '12 cuentas suspendidas · evidencia respaldada para Compliance' } },
          { kind: 'wait',    text: 'Compliance revisa evidencia',                                                       meta: 'esperando' },
          { kind: 'outcome', text: 'Pérdida evitada $18K · subnet en watchlist permanente',                             meta: '+$18K protegidos' },
        ],
      },
    ],
    reasoning: [
      'Escaneando ledger Puntos últimas 24h · 8,420 eventos.',
      'Detectada anomalía: 7 redenciones simultáneas desde mismo IP en CDMX.',
      'Score Isolation Forest: 0.94 (umbral crítico 0.85).',
      'Cuentas afectadas: 7 · monto total expuesto $24K.',
      'Congelando transacciones · solicitando verificación manual.',
      'Cross-check con lista de fraudes históricos: 2 coincidencias.',
      'Reporte enviado a Compliance · esperando dictamen 24h.',
    ],
  },
];

/* Eventos plantilla para alimentar el feed en vivo ────────────────── */
export const EVENT_TEMPLATES = {
  centinela: [
    { tone: 'success', text: '"{aliado}" reactivado · ${valor} MXN recuperados' },
    { tone: 'info',    text: 'WhatsApp enviado a {aliado} · esperando respuesta' },
    { tone: 'success', text: 'Conversión: {aliado} hizo pedido tras cupón' },
    { tone: 'warn',    text: 'Sin respuesta de {aliado} · escalando a SAT humano' },
  ],
  atlas: [
    { tone: 'info',    text: 'Nuevo cluster identificado: {aliado} · {valor} leads' },
    { tone: 'success', text: 'Leads entregados a SAT Regional' },
    { tone: 'success', text: 'Score de leads recalculado · top decil promovido' },
  ],
  mercurio: [
    { tone: 'success', text: 'Test ganó: lift +{valor}% · escalando a 100%' },
    { tone: 'info',    text: 'Nuevo experimento iniciado · cohort {valor} aliados' },
    { tone: 'warn',    text: 'Test sin lift · rollback automático' },
  ],
  vega: [
    { tone: 'info',    text: 'Forecast actualizado · Junio nacional ${valor}M' },
    { tone: 'warn',    text: 'Alerta supply: {aliado} bajo P90 forecast' },
    { tone: 'success', text: 'Re-entrenamiento exitoso · MAPE 3.4%' },
  ],
  socrates: [
    { tone: 'success', text: '{aliado} completaron video recomendado' },
    { tone: 'info',    text: '{valor} aliados recibieron recomendación personalizada' },
    { tone: 'success', text: 'Cohort de mejora: ticket promedio +18%' },
  ],
  coyote: [
    { tone: 'warn',    text: 'Anomalía detectada · transacciones congeladas' },
    { tone: 'success', text: 'Compliance confirmó fraude · {valor} bloqueados' },
    { tone: 'info',    text: 'Scan diario completado · 8,420 eventos revisados' },
  ],
};
